name: machine-learning
channels:
  - defaults
dependencies:
  - python=3.11.10
  - pip=24.2
  - ipykernel=6.29.5
  - ipython=8.27.0
  - ipywidgets=8.1.2
  - matplotlib=3.9.2
  - pandas=2.2.3
  - scikit-learn=1.5.2
  - seaborn=0.13.2
  - openpyxl=3.1.5
  - pip:
    - imbalanced-learn==0.12.4
    - xgboost==2.1.2
